### ISSUE TITLE
how to install for f-droid version of Termux???

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-gui#23] opened 2022-05-01 13:31 UTC
I installed Termux from F-droid
but F-droid build Termux it self
then i can't install Termux-GUI from F-droid and Github
can you make a release for f-droid???

**Comment by Grimler91** [comment] 2022-05-01 13:58
Duplicate of https://github.com/termux/termux-gui/issues/4

**Closed by Grimler91** 2022-05-01 13:58 UTC
