### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by anthonyprime202** [termux/termux-gui#12] opened 2022-02-15 16:01 UTC
During installation there is some kind of error.

> ![Screenshot_20220215-213000_F-Droid.png](https://user-images.githubusercontent.com/96826469/154100038-bcab7a28-eb55-4a31-b8bc-32f6102cfa2a.png)

**Comment by tareksander** [comment] 2022-02-15 17:13
Duplicate of #4

**Closed** 2022-02-15 17:13 UTC
