### ISSUE TITLE
"App not installed "  issue on Android 11 ( redmi note 10 )

### ISSUE THREAD

**Issue by sdp4377** [termux/termux-gui#16] opened 2022-03-20 11:45 UTC
# Kindly Solve this issue and give update 
![image](https://user-images.githubusercontent.com/88933367/159160466-76d0bedc-b1ef-4b46-a0ba-4463c568fc7b.png)
- when i download and installed from F-Droid website 
- i tried uninstall Termux and Termux:API and install Termux:GUI,  then it installed without any error .
- Solve this problem and please give a update for this issue .

**Comment by Grimler91** [comment] 2022-03-20 11:59
Duplicate of https://github.com/termux/termux-gui/issues/4

**Closed by Grimler91** 2022-03-20 11:59 UTC
